# Site settings
title: Infoboto
description: Clube de Robótica do Instituto Infnet

# User settings
username: INFOBOTO
user_description: Clube de Robótica do Instituto Infnet
user_title: Clube de Robótica do Instituto Infnet
email: infoboto@gmail.com
github_username: infoboto

exclude: ['package.json', 'src' , 'node_modules']
