# Site settings
title: Infoboto
description: Clube de Robótica da INFNET

# User settings
username: INFOBOTO
user_description: Clube de Robótica da INFNET
user_title: Clube de Robótica da INFNET
email: infoboto@gmail.com
github_username: infoboto

exclude: ['package.json', 'src' , 'node_modules']
