# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet

# User settings
username: INFOBOTO
user_description: 
user_title: Clube de Robótica da INFNET
email: infoboto@gmail.com
github_username:  infoboto

exclude: ['package.json', 'src' , 'node_modules']
